#!/bin/bash
packed_hosts() {
cat <<EOF
# Standard host addresses
127.0.0.1  localhost
::1        localhost ip6-localhost ip6-loopback
ff02::1    ip6-allnodes
ff02::2    ip6-allrouters
EOF
}
mount -t tmpfs /run /run
mount -t tmpfs /var /var
mount -t devtmpfs /dev /dev
mkdir /dev/pts
mount -t devpts /dev/pts /dev/pts
mount -t proc /proc /proc
mount -o remount,rw /
mkdir /workspaces
mount -t 9p -o exec host9p /workspaces
mount -t tmpfs /home/nest /home/nest
packed_hosts > /etc/hosts
ip link set lo up
if ip link | grep -q "eth0"
then
	ip link set eth0 up
	# udhcpc
fi
echo "nest ALL=(ALL:ALL) ALL" >> /etc/sudoers
#sleep 10
#clear
echo "Project is located at ~"
cd /home/nest
hostname nest
nest-client &
nc -lk -p 6061 -e bash -c "source /run_as_nc.sh; exec bash 2>&1" & #insecure but allows webapp to access bash shell with apis/extensions
sudo -u nest script -q -c "/bin/bash" /dev/null

